/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

var msRestAzure = require('ms-rest-azure');

exports.BaseResource = msRestAzure.BaseResource;
exports.CloudError = msRestAzure.CloudError;
exports.CheckNameAvailabilityRequestParameters = require('./checkNameAvailabilityRequestParameters');
exports.CheckNameAvailabilityResponse = require('./checkNameAvailabilityResponse');
exports.Sku = require('./sku');
exports.CheckAvailabilityParameters = require('./checkAvailabilityParameters');
exports.NamespacePatchParameters = require('./namespacePatchParameters');
exports.NHResource = require('./nHResource');
exports.NamespaceResource = require('./namespaceResource');
exports.SharedAccessAuthorizationRuleProperties = require('./sharedAccessAuthorizationRuleProperties');
exports.SharedAccessAuthorizationRule = require('./sharedAccessAuthorizationRule');
exports.ResourceListKeys = require('./resourceListKeys');
exports.PolicykeyResource = require('./policykeyResource');
exports.ApnsCredential = require('./apnsCredential');
exports.WnsCredential = require('./wnsCredential');
exports.GcmCredential = require('./gcmCredential');
exports.MpnsCredential = require('./mpnsCredential');
exports.AdmCredential = require('./admCredential');
exports.BaiduCredential = require('./baiduCredential');
exports.NotificationHubPatchParameters = require('./notificationHubPatchParameters');
exports.NotificationHub = require('./notificationHub');
exports.PnsCredentialsResource = require('./pnsCredentialsResource');
exports.SubResource = require('./subResource');
exports.Resource = require('./resource');
exports.ProxyResource = require('./proxyResource');
exports.TrackedResource = require('./trackedResource');
exports.NamespaceListResult = require('./namespaceListResult');
exports.SharedAccessAuthorizationRuleListResult = require('./sharedAccessAuthorizationRuleListResult');
exports.NotificationHubListResult = require('./notificationHubListResult');
