/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * The properties of the resource
 *
 * @extends models['BaseResource']
 */
class NHResource extends models['BaseResource'] {
  /**
   * Create a NHResource.
   * @member {object} [sku] The sku of the created namespace
   * @member {string} [sku.name] Name of the notification hub sku. Possible
   * values include: 'Free', 'Basic', 'Standard'
   * @member {string} [sku.tier] The tier of particular sku
   * @member {string} [sku.size] The Sku size
   * @member {string} [sku.family] The Sku Family
   * @member {number} [sku.capacity] The capacity of the resource
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of NHResource
   *
   * @returns {object} metadata of NHResource
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'NHResource',
      type: {
        name: 'Composite',
        className: 'NHResource',
        modelProperties: {
          sku: {
            required: false,
            serializedName: 'sku',
            type: {
              name: 'Composite',
              className: 'Sku'
            }
          }
        }
      }
    };
  }
}

module.exports = NHResource;
