/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * NotificationHub patch parameters.
 *
 */
class NotificationHubPatchParameters {
  /**
   * Create a NotificationHubPatchParameters.
   * @member {array} [authorizationRules] The AuthorizationRules of the created
   * NotificationHub
   * @member {object} [apnsCredential] The ApnsCredential of the created
   * NotificationHub
   * @member {string} [apnsCredential.apnsCertificate] The APNS certificate.
   * @member {string} [apnsCredential.certificateKey] The certificate key.
   * @member {string} [apnsCredential.endpoint] The endpoint of this
   * credential.
   * @member {string} [apnsCredential.thumbprint] The Apns certificate
   * Thumbprint
   * @member {string} [apnsCredential.keyId] A 10-character key identifier
   * (kid) key, obtained from your developer account
   * @member {string} [apnsCredential.bundleId] Id that uniquely identifies an
   * Application Bundle on a device or simulator
   * @member {string} [apnsCredential.teamId] A unique 10 character string
   * generated by Apple thats assigned to your team
   * @member {string} [apnsCredential.token] Provider Authentication Token,
   * obtained through your developer account
   * @member {object} [wnsCredential] The WnsCredential of the created
   * NotificationHub
   * @member {string} [wnsCredential.packageSid] The package ID for this
   * credential.
   * @member {string} [wnsCredential.secretKey] The secret key.
   * @member {string} [wnsCredential.windowsLiveEndpoint] The Windows Live
   * endpoint.
   * @member {object} [gcmCredential] The GcmCredential of the created
   * NotificationHub
   * @member {string} [gcmCredential.gcmEndpoint] The GCM endpoint.
   * @member {string} [gcmCredential.googleApiKey] The Google API key.
   * @member {object} [mpnsCredential] The MpnsCredential of the created
   * NotificationHub
   * @member {string} [mpnsCredential.mpnsCertificate] The MPNS certificate.
   * @member {string} [mpnsCredential.certificateKey] The certificate key for
   * this credential.
   * @member {string} [mpnsCredential.thumbprint] The Mpns certificate
   * Thumbprint
   * @member {object} [admCredential] The AdmCredential of the created
   * NotificationHub
   * @member {string} [admCredential.clientId] The client identifier.
   * @member {string} [admCredential.clientSecret] The credential secret access
   * key.
   * @member {string} [admCredential.authTokenUrl] The URL of the authorization
   * token.
   * @member {object} [baiduCredential] The BaiduCredential of the created
   * NotificationHub
   * @member {string} [baiduCredential.baiduApiKey] Baidu Api Key.
   * @member {string} [baiduCredential.baiduEndPoint] Baidu Endpoint.
   * @member {string} [baiduCredential.baiduSecretKey] Baidu Secret Key
   */
  constructor() {
  }

  /**
   * Defines the metadata of NotificationHubPatchParameters
   *
   * @returns {object} metadata of NotificationHubPatchParameters
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'NotificationHubPatchParameters',
      type: {
        name: 'Composite',
        className: 'NotificationHubPatchParameters',
        modelProperties: {
          authorizationRules: {
            required: false,
            serializedName: 'authorizationRules',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SharedAccessAuthorizationRulePropertiesElementType',
                  type: {
                    name: 'Composite',
                    className: 'SharedAccessAuthorizationRuleProperties'
                  }
              }
            }
          },
          apnsCredential: {
            required: false,
            serializedName: 'apnsCredential',
            type: {
              name: 'Composite',
              className: 'ApnsCredential'
            }
          },
          wnsCredential: {
            required: false,
            serializedName: 'wnsCredential',
            type: {
              name: 'Composite',
              className: 'WnsCredential'
            }
          },
          gcmCredential: {
            required: false,
            serializedName: 'gcmCredential',
            type: {
              name: 'Composite',
              className: 'GcmCredential'
            }
          },
          mpnsCredential: {
            required: false,
            serializedName: 'mpnsCredential',
            type: {
              name: 'Composite',
              className: 'MpnsCredential'
            }
          },
          admCredential: {
            required: false,
            serializedName: 'admCredential',
            type: {
              name: 'Composite',
              className: 'AdmCredential'
            }
          },
          baiduCredential: {
            required: false,
            serializedName: 'baiduCredential',
            type: {
              name: 'Composite',
              className: 'BaiduCredential'
            }
          }
        }
      }
    };
  }
}

module.exports = NotificationHubPatchParameters;
