/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Description of a Namespace AuthorizationRules.
 *
 * @extends models['NHResource']
 */
class SharedAccessAuthorizationRule extends models['NHResource'] {
  /**
   * Create a SharedAccessAuthorizationRule.
   * @member {array} [rights] The rights associated with the rule.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of SharedAccessAuthorizationRule
   *
   * @returns {object} metadata of SharedAccessAuthorizationRule
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SharedAccessAuthorizationRule',
      type: {
        name: 'Composite',
        className: 'SharedAccessAuthorizationRule',
        modelProperties: {
          sku: {
            required: false,
            serializedName: 'sku',
            type: {
              name: 'Composite',
              className: 'Sku'
            }
          },
          rights: {
            required: false,
            serializedName: 'properties.rights',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AccessRightsElementType',
                  type: {
                    name: 'Enum',
                    allowedValues: [ 'Manage', 'Send', 'Listen' ]
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = SharedAccessAuthorizationRule;
